CREATE TABLE `mail` (
	`id` VARCHAR(50) NULL DEFAULT NULL,
	`touser` VARCHAR(50) NULL DEFAULT NULL,
	`ahost` VARCHAR(50) NULL DEFAULT NULL,
	`aport` VARCHAR(50) NULL DEFAULT NULL,
	`afrom` VARCHAR(50) NULL DEFAULT NULL,
	`inserttime` VARCHAR(50) NULL DEFAULT NULL,
	`cg` VARCHAR(50) NULL DEFAULT NULL,
	`asubject` VARCHAR(50) NULL DEFAULT NULL,
	`ts` VARCHAR(50) NULL DEFAULT NULL,
	`batch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
